### ISSUE TITLE
Can't launch in eclipse

### ISSUE THREAD

**Issue by ccjon** [jmhofer/eCobertura#16]
Can't find this mentioned elsewhere ..... 
I just installed and tried to 'Cover As' a unit test  ....' get this:
"java.lang.NoSuchMethodError: java.util.Arrays.copyOf([Ljava/lang/Object;I)[Ljava/lang/Object;...."

... hoping maybe you'd recognize it right away....

Fedora 12 (latest updates)
eclipse 3.5.2 build 20100218-1602

**Comment by austinchad** [comment]
I'm using Eclipse 3.6 and specifying a 1.6 JRE in the launch configuration, but it the launch is picking up the Java version from my Path instead which is JRE 1.5 which does not have copyOf() method.

**Comment by ccjon** [comment]
Good idea... lead to the fix but but interestingly looks like my tests are configured to launch with 1.6 as well, and Coburtura Coverage launch config seems to mimic the test config's.... but the the IDE was launched in 1.5 :)

**Comment by ccjon** [comment]
thanks btw
