### ISSUE TITLE
Add ability to sort the coverage session results

### ISSUE THREAD

**Issue by radaczynski** [jmhofer/eCobertura#6]
I would like to be able to sort the coverage session view by any column that is in the view.

**Comment by jmhofer** [comment]
Good idea. - I wonder how that would work together with the tree structure of the packages, however...

**Comment by jmhofer** [comment]
The next release will at least introduce a default alphabetic sorting of the view (which I thought had already worked)...

**Comment by jmhofer** [comment]
Alright, I implemented this completely, as it was easier than I first thought. - You can now sort by any column in the coverage session view, either ascending or descending. This will be in 0.9.7.

**Comment by jmhofer** [comment]
I close this, as it's in 0.9.7 and released.

**Comment by mjviljan** [comment]
When I try to sort the results by either line or branch coverage percentage, they are sorted based on the number (of lines or branches, i.e. the first column in each category). Should the sorting work on the percentage columns also?

(eCobertura version 0.9.8.201007202152; Eclipse version Helios, build 20100617-1415)
